export const TYPES = {
  SET_SEARCH_FILTERS: "SET_SEARCH_FILTERS",
  SET_LIVESEARCH_FILTERS: "SET_LIVESEARCH_FILTERS",
  SET_PREV_PAGE: "SET_PREV_PAGE",
  SET_NEXT_PAGE: "SET_NEXT_PAGE",
  SET_DEFAULT_PAGE: "SET_DEFAULT_PAGE",
  OPEN_SEARCH_DROPDOWN: 'OPEN_SEARCH_DROPDOWN',
  CLOSE_SEARCH_DROPDOWN: 'CLOSE_SEARCH_DROPDOWN',
};
