export const TYPES = {
  GET_MOVIES: "GET_MOVIES",
  GET_MOVIES_SUCCESS: "GET_MOVIES_SUCCESS",
  GET_TOTAL_MOVIES: "GET_TOTAL_MOVIES",
  GET_MOVIES_ERROR: "GET_MOVIES_ERROR",
  GET_LIVESEARCH_MOVIES: "GET_LIVESEARCH_MOVIES",
  GET_LIVESEARCH_MOVIES_SUCCESS: "GET_LIVESEARCH_MOVIES_SUCCESS",
  GET_LIVESEARCH_MOVIES_ERROR: "GET_LIVESEARCH_MOVIES_ERROR",
};
